name: Build on Ubuntu
on: 
  workflow_dispatch:
    
  push:
    branches:
      - main

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

  pull_request:
    branches:
      - main
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install git autoconf automake pkg-config build-essential cmake liblua5.1-0-dev libsqlite3-dev libmysqlclient-dev 
          libxml2-dev libgmp3-dev libboost-filesystem-dev libboost-regex-dev libboost-thread-dev libboost-iostreams-dev
          gcc-10 g++-10 cpp-10 wget libcrypto++-dev libpugixml-dev libgomp1 libfmt-dev zlib1g-dev

      - name: Build with cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          configure-options: -DUSE_LUAJIT=on
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 2

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs